Fix holdings example
I didn't had the chance to test it finally, but you will get this error if you want to execute the example:
```
f.get_holdings()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    f.get_holdings()
TypeError: get_holdings() missing 1 required positional argument: 'account'
```
According to this line https://github.com/raphaelm/python-fints/blob/master/fints/client.py#L168, this should fix the bug.